on:
  push:
    branches:
    - UserManagementService
env:
  DOTNET_CORE_VERSION: 7.0.x
  CONTAINER_APP_NAME: usermanagementservice-container-app
  CONTAINER_APP_ENVIRONMENT_NAME: managedEnvironment-LibraryManageme-a030
  RESOURCE_GROUP: LibraryManagement
  CONTAINER_REGISTRY_NAME: catalogcontainerregistry
  CONTAINER_REGISTRY_LOGIN_SERVER: catalogcontainerregistry.azurecr.io
jobs:
  BuildAndDeployContainerApp:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.managedEnvironment_LibraryManageme_a030_SPN }}
    - name: Container App deploy
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}
        acrName: ${{ env.CONTAINER_REGISTRY_NAME }}
        acrUsername: ${{ secrets.CatalogContainerRegistry_USERNAME_504C }}
        acrPassword: ${{ secrets.CatalogContainerRegistry_PASSWORD_504C }}
        imageToBuild: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
        containerAppName: ${{ env.CONTAINER_APP_NAME }}
        containerAppEnvironment: ${{ env.CONTAINER_APP_ENVIRONMENT_NAME }}
        resourceGroup: ${{ env.RESOURCE_GROUP }}
        environmentVariables: | 
          ASPNETCORE_ENVIRONMENT=Development
          ConnectionStrings__UserContext='${{ secrets.ConnectionStrings__UserContext }}'